version: '3'
services:
  apollo:
    image: cumplo/srm-apollo-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    volumes:
      - ./apollo-server-app:/apollo
      - /apollo/node_modules/
    command: >
      sh -c "serverless --host 0.0.0.0 --httpPort 4000 offline start --stage development"
    environment:
      - API_SRM=http://api-srm-cumplo:8000/
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: apollonet
