version: '3'
services:
  apollo:
    build: .
    ports:
      - "4001:4000"
    volumes:
    - ./apollo-server-app:/source
    - /source/node_modules
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: apollonet
