# serverless.yml

service:
  name: srm-apollo
plugins:  
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  environment:
    API_SRM: https://api-srm.${self:provider.stage}.cumplo.cl
functions:
  graphql:
    handler: server.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
  customDomain:
    basePath: ""
    domainName: srm-apollo-server.${self:provider.stage}.cumplo.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'